import javafx.stage.*;
import javafx.scene.*;
import javafx.scene.layout.*;
import javafx.scene.control.*;
import javafx.geometry.*;

/**
 * This class implements the alert box that forces users to pick a job
 * for any questions that require the user to input a job. By asking the
 * user to pick from the top ~100-200 jobs, we're also (for the most part) 
 * reducing the chance of a job that didn't have any applications to be picked.
 * @author adi
 *
 */
public class JobAlertBox {

    static String answer;
    
    public static String display() {

        Stage window = new Stage();

        //block events to other windows
        window.initModality(Modality.APPLICATION_MODAL);
        
        window.setTitle("H-1B Data Analyzer | Pick Your Job");
        window.setMinWidth(750);

        Label label = new Label();
        label.setText("Pick the job that you want to analyze: ");
        
        //job drop down box
        ChoiceBox<String> allJobs = new ChoiceBox<>();
        allJobs.getItems().addAll(".NET DEVELOPER","ACCOUNTANT","ADVISORY ASSOCIATE",
                "ADVISORY CONSULTANT","ADVISORY MANAGER","ADVISORY SENIOR",
                "ADVISORY SENIOR ASSOCIATE","ADVISORY STAFF","ANALYST","ANALYST-TESTING",
                "APPLICATION DEVELOPER","APPLICATION ENGINEER","APPLICATION PROGRAMMER",
                "APPLICATIONS CONSULTANT","APPLICATIONS CONSULTANT 2","APPLICATIONS DEVELOPER",
                "APPLICATIONS ENGINEER","ARCHITECT","ARCHITECT LEVEL 2","ARCHITECTURAL DESIGNER",
                "ASSISTANT PROFESSOR","ASSISTANT VICE PRESIDENT","ASSOCIATE",
                "ASSOCIATE CONSULTANT - US","ASSOCIATE SOFTWARE ENGINEER","ASSURANCE ASSOCIATE",
                "ASSURANCE SENIOR","ASSURANCE STAFF","BUDGET ANALYST","BUSINESS ANALYST",
                "BUSINESS DEVELOPMENT MANAGER","BUSINESS INTELLIGENCE ANALYST",
                "BUSINESS SYSTEM ANALYST","BUSINESS SYSTEMS ANALYST","BUSINESS SYSTEMS ANALYST 2",
                "BUSINESS SYSTEMS ANALYST 3","BUSINESS TECHNOLOGY ANALYST","CHIEF CREATIVE OFFICER",
                "CHIEF DIGITAL OFFICER","CHIEF EXECUTIVE OFFICER","CHIEF EXPERIENCE OFFICER",
                "CHIEF FINANCIAL OFFICER","CHIEF INFORMATION OFFICER","CHIEF INVESTMENT OFFICER",
                "CHIEF MARKETING OFFICER","CHIEF MEDICAL OFFICER","CHIEF OPERATING OFFICER",
                "CHIEF PRODUCT OFFICER","CHIEF TECHNOLOGY OFFICER","CIVIL ENGINEER",
                "CLINICAL ASSISTANT PROFESSOR","COMPONENT DESIGN ENGINEER","COMPUTER PROGRAMMER",
                "COMPUTER PROGRAMMER ANALYST","COMPUTER PROGRAMMER/CONFIGURER 2","COMPUTER PROGRAMMERS",
                "COMPUTER SOFTWARE ENGINEER","COMPUTER SPECIALIST",
                "COMPUTER SPECIALIST/SYSTEM SUPPORT AND DEVELOPMENT ADMIN 2",
                "COMPUTER SPECIALIST/TESTING AND QUALITY ANALYST 2","COMPUTER SYSTEM ANALYST",
                "COMPUTER SYSTEM ENGINEER","COMPUTER SYSTEMS ANALYST","COMPUTER SYSTEMS ANALYST 2",
                "COMPUTER SYSTEMS ANALYST 3","COMPUTER SYSTEMS ANALYSTS","COMPUTER SYSTEMS ENGINEER",
                "CONSULTANT","CONSULTANT - US","CONSULTANT LEVEL 3","DATA ANALYST","DATA ANALYST 2",
                "DATA SCIENTIST","DATABASE ADMINISTRATOR","DENTIST","DESIGN ENGINEER","DESIGNER","DEVELOPER",
                "DEVELOPER USER INTERFACE","ELECTRICAL ENGINEER","ELEMENTARY BILINGUAL TEACHER","ENGINEER",
                "ETL DEVELOPER","FINANCIAL ANALYST","FUNCTIONAL CONSULTANT","GRAPHIC DESIGNER","HARDWARE ENGINEER",
                "HOSPITALIST","HOSPITALIST PHYSICIAN","INDUSTRIAL DESIGNER","INDUSTRIAL ENGINEER","INSTRUCTOR",
                "IT CONSULTANT","IT PROJECT MANAGER","IT SPECIALIST","JAVA DEVELOPER","LAW CLERK","LEAD CONSULTANT",
                "LEAD CONSULTANT - US","LEAD ENGINEER","LEAD SOFTWARE ENGINEER","LECTURER","MANAGEMENT ANALYST",
                "MANAGER","MANAGER JC50","MANAGING CONSULTANT","MANUFACTURING ENGINEER","MARKET RESEARCH ANALYST",
                "MARKETING MANAGER","MARKETING SPECIALIST","MECHANICAL ENGINEER","MEDICAL RESIDENT",
                "MEDICAL TECHNOLOGIST","MEMBER OF TECHNICAL STAFF","MTS 1","NEPHROLOGIST","NETWORK ADMINISTRATOR",
                "NETWORK AND COMPUTER SYSTEMS ADMINISTRATOR","NETWORK ENGINEER","OCCUPATIONAL THERAPIST",
                "OPERATIONS RESEARCH ANALYST","ORACLE DATABASE ADMINISTRATOR","PHARMACIST","PHYSICAL THERAPIST",
                "PHYSICIAN","POSTDOCTORAL ASSOCIATE","POSTDOCTORAL FELLOW","POSTDOCTORAL RESEARCH ASSOCIATE",
                "POSTDOCTORAL RESEARCH FELLOW","POSTDOCTORAL RESEARCHER","POSTDOCTORAL SCHOLAR","PRINCIPAL CONSULTANT",
                "PRINCIPAL CONSULTANT - US","PRINCIPAL SOFTWARE ENGINEER","PROCESS ENGINEER","PRODUCT ENGINEER",
                "PRODUCT MANAGER","PROGRAM MANAGER","PROGRAMMER","PROGRAMMER / ANALYST","PROGRAMMER ANALYST",
                "PROGRAMMER ANALYST - I","PROGRAMMER ANALYST - II","PROGRAMMER ANALYST LEVEL 1",
                "PROGRAMMER/ DEVELOPER 2","PROGRAMMER/ANALYST","PROGRAMMER/DEVELOPER","PROJECT ENGINEER",
                "PROJECT LEAD","PROJECT MANAGER","PROJECT MANAGER - III","PROJECT MANAGER - IV",
                "PROJECT MANAGER - US","PROJECT MANAGER 3","QA ANALYST","QA ENGINEER","QA TESTER","QUALITY ANALYST",
                "QUALITY ASSURANCE ANALYST","QUALITY ASSURANCE ENGINEER","QUALITY ENGINEER","QUANTITATIVE ANALYST",
                "RESEARCH ANALYST","RESEARCH ASSISTANT PROFESSOR","RESEARCH ASSOCIATE","RESEARCH FELLOW",
                "RESEARCH SCIENTIST","RESIDENT PHYSICIAN","RF ENGINEER","SALES ENGINEER","SALESFORCE DEVELOPER",
                "SAP CONSULTANT","SENIOR ANALYST","SENIOR APPLICATION DEVELOPER","SENIOR ASSOCIATE",
                "SENIOR BUSINESS ANALYST","SENIOR CONSULTANT","SENIOR DATABASE ADMINISTRATOR","SENIOR DEVELOPER",
                "SENIOR ENGINEER","SENIOR JAVA DEVELOPER","SENIOR MANAGER JC45","SENIOR PRODUCT MANAGER",
                "SENIOR PROGRAMMER ANALYST","SENIOR PROJECT MANAGER - US","SENIOR SOFTWARE DEVELOPER",
                "SENIOR SOFTWARE ENGINEER","SENIOR SOLUTION ENGINEER","SENIOR SYSTEMS ANALYST","SENIOR SYSTEMS ANALYST JC60",
                "SENIOR SYSTEMS ENGINEER","SENIOR TECHNICAL CONSULTANT","SENIOR TECHNOLOGY ARCHITECT - US",
                "SOFTWARE APPLICATIONS DEVELOPER","SOFTWARE ARCHITECT","SOFTWARE DESIGN ENGINEER",
                "SOFTWARE DEVELOPER","SOFTWARE DEVELOPER","SOFTWARE DEVELOPER","SOFTWARE DEVELOPMENT ENGINEER",
                "SOFTWARE DEVELOPMENT ENGINEER I","SOFTWARE DEVELOPMENT ENGINEER II","SOFTWARE ENGINEER",
                "SOFTWARE ENGINEER & TESTER","SOFTWARE ENGINEER 2","SOFTWARE ENGINEER 3","SOFTWARE ENGINEER II",
                "SOFTWARE ENGINEER III","SOFTWARE PROGRAMMER","SOFTWARE PROGRAMMER ANALYST","SOFTWARE QA ENGINEER",
                "SOFTWARE QUALITY ASSURANCE ENGINEER","SOFTWARE SYSTEMS ENGINEER","SOFTWARE TEST ENGINEER",
                "SOLUTION ARCHITECT","SOLUTION ENGINEER","SOLUTIONS ARCHITECT","SPECIALIST MASTER",
                "SPECIALIST SENIOR","SR. PROGRAMMER ANALYST","SR. SOFTWARE DEVELOPER","SR. SOFTWARE ENGINEER",
                "STAFF ACCOUNTANT","STAFF ENGINEER","STAFF SOFTWARE ENGINEER","SYSTEM ADMINISTRATOR",
                "SYSTEM ANALYST","SYSTEM ANALYST JC65","SYSTEM ENGINEER","SYSTEMS ADMINISTRATOR",
                "SYSTEMS ANALYST","SYSTEMS ANALYST - II","SYSTEMS ANALYST I","SYSTEMS ANALYST JC65",
                "SYSTEMS ANALYSTS","SYSTEMS ENGINEER","SYSTEMS ENGINEER - US","TAX SENIOR","TAX STAFF",
                "TEACHER","TECHNICAL ANALYST","TECHNICAL ARCHITECT","TECHNICAL CONSULTANT","TECHNICAL LEAD",
                "TECHNICAL RECRUITER","TECHNICAL TEST LEAD - US","TECHNOLOGY ANALYST - US",
                "TECHNOLOGY ARCHITECT - US","TECHNOLOGY LEAD - US","TECHNOLOGY LEAD - US - PRACTITIONER",
                "TEST ANALYST","TEST ANALYST - US","TEST CONSULTANT","TEST CONSULTANT 2","TEST ENGINEER",
                "TEST ENGINEER - US","TEST ENGINEER LEVEL 2","TEST LEAD","TEST SPECIALIST",
                "VALIDATION ENGINEER","VICE PRESIDENT","WEB DEVELOPER");
        
        allJobs.setValue(".NET DEVELOPER");
        
        Button closeButton = new Button("Confirm");
        
        closeButton.setOnAction (e -> {
            answer = allJobs.getValue();
            window.close(); 
        });

        VBox layout = new VBox(25);
        layout.setPadding(new Insets(100, 0, 100, 0));
        layout.getChildren().addAll(label, allJobs, closeButton);
        layout.setAlignment(Pos.CENTER);

        //display window and wait for it to be closed before returning
        Scene alertScene = new Scene(layout);
        
        String css = "file:resources/style.css";
        alertScene.getStylesheets().add(css);
        
        window.setScene(alertScene);
        window.showAndWait();
        
        return answer;
    }

}